### ISSUE TITLE
overall visual site design

### ISSUE THREAD

**Issue by dviramontes** [mmmanyfold/this-machine-has-a-soul#8]
- site identity
- layout 
- content 
- pick a color scheme
- how do we want to render the content
- how do we make it machine like (think theme)
- pick font

**Comment by eemshi** [comment]
http://exhibitions.guggenheim.org/storylines/tag/consumerism
http://wemakesomething.com/
http://welcometotheuniverse.net/
http://www.artplaceamerica.org/
